import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePDFStatement = (user, expenses, incomes, startDate, endDate) => {
  const doc = new jsPDF();
  const title = 'FINANCIAL EXPENSE STATEMENT';

  // Calculate totals
  const totalIncome = incomes.reduce((sum, item) => sum + item.amount, 0);
  const totalExpense = expenses.reduce((sum, item) => sum + item.amount, 0);
  const netBalance = totalIncome - totalExpense;

  // Header Colors & Styling
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(0, 0, 210, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(title, 14, 22);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Smart Multi-User Expense Tracker System', 14, 30);
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-US', { dateStyle: 'medium' })}`, 140, 30);

  // User Details & Date Range Section
  doc.setTextColor(33, 37, 41);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Account Details:', 14, 48);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${user?.name || 'N/A'}`, 14, 55);
  doc.text(`Email: ${user?.email || 'N/A'}`, 14, 61);

  doc.setFont('helvetica', 'bold');
  doc.text('Statement Period:', 120, 48);
  doc.setFont('helvetica', 'normal');
  doc.text(`From: ${startDate || 'Beginning'}  To: ${endDate || 'Present'}`, 120, 55);

  // Summary Box
  doc.setFillColor(241, 245, 249); // Slate-100
  doc.roundedRect(14, 68, 182, 24, 3, 3, 'F');

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text('TOTAL INCOME', 24, 76);
  doc.text('TOTAL EXPENSE', 84, 76);
  doc.text('NET REMAINING BALANCE', 144, 76);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(16, 185, 129); // Green
  doc.text(`RS ${totalIncome.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 24, 84);

  doc.setTextColor(239, 68, 68); // Red
  doc.text(`RS ${totalExpense.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 84, 84);

  doc.setTextColor(netBalance >= 0 ? 16 : 239, netBalance >= 0 ? 185 : 68, netBalance >= 0 ? 129 : 68);
  doc.text(`RS ${netBalance.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, 144, 84);

  // Itemized Expense Table
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Itemized Expense Breakdown', 14, 102);

  const tableData = expenses.map((exp, index) => [
    index + 1,
    exp.date,
    exp.title,
    exp.category,
    exp.payment_method,
    `RS ${exp.amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
  ]);

  autoTable(doc, {
    startY: 106,
    head: [['#', 'Date', 'Description / Item', 'Category', 'Payment Mode', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [79, 70, 229], // Indigo-600
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 26 },
      2: { cellWidth: 55 },
      3: { cellWidth: 32 },
      4: { cellWidth: 30 },
      5: { cellWidth: 29, halign: 'right' }
    }
  });

  // Footer / Page numbers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${i} of ${pageCount} - Confidential Financial Document - Generated by ExpenseTracker App`,
      105,
      288,
      { align: 'center' }
    );
  }

  doc.save(`Expense_Statement_${user?.name?.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
};
